### ISSUE TITLE
Code Review #1

### ISSUE THREAD

**Issue by VadimMoschenkov** [kane2033/RecipiesKODE#1]
1. `com.kode.recipes.presentation.recipe.RecipesListViewModel#searchByField` :
 В функции много повторяющегося кода во всех 3х ветках `when`

```kotlin
                unfilteredRecipes.forEach {
                    if (it.description?.toLowerCase(defaultLocale)
                            ?.contains(filterPattern) == true
                    ) {
                        filteredList.add(it)
                    }
                }

```

Можно было записать компактнее 

```kotlin
                unfilteredRecipes.filter { it.name.toLowerCase(defaultLocale).contains(filterPattern) }
```

2. `SortByBottomSheetFragment` и `SearchByBottomSheetDialog` используют вью модель для управления поиском, тут было бы лучше что бы эти фрагменты через колбек вернули результат выбора, а что с ним делать дальше решил бы фрагмент, это позволило бы эти фрагменты переиспользовать, а так они привязаны к конкретному экрану. 
Это замечание можно не исправлять

3. `RecipesListViewModel` в данный момент вью модель занимается и поиском и сортировкой списка, отличным решением было бы отдать эту обязанность репозиторию

4. Не обработаны ошибки, в случае отключения интернета список просто не показывается - пользователь должен всегда понимать что происходит, т.е. интерфейс должен иметь отклик и показать пользователю например: "Не удалось загрузить рецепты" и возможность повторить запрос

5. Кнопки шаринга и "избранное" не работают. Если в на экране есть кнопка она должна работать или сообщать что функционал еще в разработке

6. `RecipeDetailsFragment` весь код написан в `onViewCreated` например функцию в адаптера -  `imageClickedInterface` можно было вынести в отдельный метод, так код стал бы более читаемым.
Кроме этого тут используется хардкод, например:
```kotlin
               val bundle = bundleOf(
                    "urls" to urls,
                    "index" to imageCountTabLayout.selectedTabPosition
                )
```
Ключи `urls` и `index` стоило вынести в константы.

7. `RecipeImagesFullScreenFragment` код сохранения изображения выглядит странно и избыточно:
```kotlin
            binding.apply {
                // Получаем viewholder отображаемого view
                val currentViewHolder =
                    (imageViewPager[0] as RecyclerView).findViewHolderForAdapterPosition(
                        imageCountTabLayout.selectedTabPosition
                    )
                // Получаем imageview с отображаемой картинкой
                val imageView = currentViewHolder?.itemView?.findViewById<ImageView>(R.id.imageView)
                // Сохраняем в галерею
                imageView?.saveImageToPictures()
            }
```
фрагменту совершенно не обязательно знать о том как организован адаптер списка использует ли он вью холдер или нет, тут лучше было бы спросить позицию  у viewPager `binding.imageViewPager.currentItem` и далее уже либо у адаптера получить картинку по позиции либо выбрать из списка

8. Поиск открывается в 2 клика, первый раз нужно нажать на иконку поиска и второй раз в виджет чтобы открылась клавиатура

9. `RecipeRepositoryImpl` и\или юзкейсы кто то из них должен брать на себя больше логики, например по поиску и сортировке - тут уже тебе решать чем является поиск и сортировка - особенностью данных или же бизнес-логикой,  но уж точно не особенностью интерфейса.

**Comment by kane2033** [comment]
Приложил pull request к issue, в нем видны все коммиты, направленные на исправления ошибок. Для наглядности, пройдусь по каждому пункту.

1. (3, 9) Логика поиска и сортировки перемещена в соответствующие UseCase: `com.kode.recipes.domain.recipe.interactor.SearchRecipes` и `com.kode.recipes.domain.recipe.interactor.SortRecipes`.

2. Поменять на коллбэк не успел, надеюсь попробовать на следующей итерации.

3. См. п.1.

4. Добавлен диалоговый фрагмент с отображением ошибки `com.kode.recipes.ui.base.FailureFragment`.
Используется в `com.kode.recipes.ui.base.BaseFragment#handleFailure`.

5. Так как нет требования о реализации этих фич, а в дизайне иконки есть, при нажатии на них появляется toast сообщение о том, что фичи в разработке.

6. Вынес код imageClickedInterface в функцию, стало более читаемо. 
Также избавился от хардкода, константы для экрана деталей рецепта вынесены в `com.kode.recipes.presentation.recipe.RecipeDetailsConstants`.

7.  Изменил получение картинки в соответствие с комментарием - теперь по позиции viewPager беру url картинки.
Логика скачивания картинки вынесена в репозиторий 'com.kode.recipes.data.recipe.repository.ImageRepositoryImpl' и используется в юзкейсе `com.kode.recipes.domain.recipe.interactor.SaveImageToPictures`. Сначала картинка скачивается с помощью Picasso, а потом сохраняется на устройство в папку "Pictures".

8. Заменил `android.widget.SearchView` на `androidx.appcompat.widget.SearchView`, поиск стал открываться в один клик.

9. См. п.1.
